[package]
name = "native-runner"
version = "1.0.0"
edition = "2021"
description = "A native runner for the Archytex editor"
authors = ["Gulyás Arnold"]
default-run = "native-runner"

[dependencies]
winit = "0"
app = { path = "../app" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"